"""apn number

Revision ID: 1ea9e8fa1116
Revises: 284a8c5412a1
Create Date: 2026-04-11 23:21:27.976700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea9e8fa1116'
down_revision: Union[str, None] = '284a8c5412a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_appointments_appointment_number'), 'appointments', ['appointment_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_column('appointments', 'appointment_number')
    # ### end Alembic commands ###
