"""clinic group again

Revision ID: 92e0ade093fd
Revises: eef7407a7e16
Create Date: 2026-04-10 21:15:48.042311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e0ade093fd'
down_revision: Union[str, None] = 'eef7407a7e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('main_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_groups_slug'), 'clinic_groups', ['slug'], unique=True)
    op.add_column('clinics', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('clinics', sa.Column('branch_name', sa.String(), nullable=True))
    op.add_column('clinics', sa.Column('branch_slug', sa.String(), nullable=True))
    op.add_column('clinics', sa.Column('city', sa.String(), nullable=True))
    op.add_column('clinics', sa.Column('area', sa.String(), nullable=True))
    op.add_column('clinics', sa.Column('search_phone', sa.String(), nullable=True))
    op.add_column('clinics', sa.Column('join_code', sa.String(length=20), nullable=True))
    op.add_column('clinics', sa.Column('is_discoverable', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('is_default_branch', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_clinics_branch_slug'), 'clinics', ['branch_slug'], unique=True)
    op.create_index(op.f('ix_clinics_group_id'), 'clinics', ['group_id'], unique=False)
    op.create_index(op.f('ix_clinics_join_code'), 'clinics', ['join_code'], unique=True)
    op.create_index(op.f('ix_clinics_search_phone'), 'clinics', ['search_phone'], unique=False)
    op.create_foreign_key(None, 'clinics', 'clinic_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clinics', type_='foreignkey')
    op.drop_index(op.f('ix_clinics_search_phone'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_join_code'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_group_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_branch_slug'), table_name='clinics')
    op.drop_column('clinics', 'is_default_branch')
    op.drop_column('clinics', 'is_discoverable')
    op.drop_column('clinics', 'join_code')
    op.drop_column('clinics', 'search_phone')
    op.drop_column('clinics', 'area')
    op.drop_column('clinics', 'city')
    op.drop_column('clinics', 'branch_slug')
    op.drop_column('clinics', 'branch_name')
    op.drop_column('clinics', 'group_id')
    op.drop_index(op.f('ix_clinic_groups_slug'), table_name='clinic_groups')
    op.drop_table('clinic_groups')
    # ### end Alembic commands ###
